### ISSUE TITLE
Audio Data

### ISSUE THREAD

**Issue by vinodkkurmi** [miqueltubau/Wav2Pix#1]
hi @miqueltubau  Where can I get the audio dataset? The repo only provided the images, not the audio files. Can you please help regarding this?

**Comment by miqueltubau** [comment]
Hey there!

I am quite busy these days, but I’ll contact you this weekand!

Miquel

**Comment by Monica-hr** [comment]
Thank you for your code,But,Where can I get the audio dataset?

**Comment by miqueltubau** [comment]
To begin with, let me apologise for answering you, but specially @vinodkkurmi, so late.
Regarding your question, I have double checked that the problem is only a
github displaying issue. They audios are still there if you clone the repo!

Regards,
